### ISSUE TITLE
Test performance in Noetic

### ISSUE THREAD

**Issue by jcnorby** [robomechanics/quad-sdk#192]

**Comment by soldierofhell** [comment]
Hi @jcnorby , I'm interested in Noetic. Is there any work started?

**Comment by soldierofhell** [comment]
Thanks. In the meantime I've managed to run the stack on Noetic (although I definitely haven't tested everything). I've got a question: what is the purpose of putting apt install ros-distro-package into setup_deps.sh (instead of using rosdep directly)?

**Comment by jcnorby** [comment]
Glad to hear it seems mostly straightforward! And no particular reason other than that was the default way we had been building external packages so that's how they were added to the install scripts. We may have an additional update in the future which optimizes those setup scripts.

**Comment by ardalantj** [comment]
@soldierofhell Can this issue be closed?

**Comment by ardalantj** [comment]
Will close this issue due to inactivity. If there is a problem, open a new issue
