### ISSUE TITLE
gazebo: symbol lookup error

### ISSUE THREAD

**Issue by jcnorby** [robomechanics/quad-sdk#200]
This causes gazebo to crash when launching the sim. It has a known fix (described [here](https://answers.gazebosim.org//question/22071/symbol-lookup-error-both-instalation-methods/)), but should we include this ignition math upgrade in our setup scripts automatically?

**Comment by samjupo** [comment]
> This causes gazebo to crash when launching the sim. It has a known fix (described [here](https://answers.gazebosim.org//question/22071/symbol-lookup-error-both-instalation-methods/)), but should we include this ignition math upgrade in our setup scripts automatically?

I have solved this problem with **sudo apt upgrade libignition-math2**  refer here https://answers.gazebosim.org//question/22071/symbol-lookup-error-both-instalation-methods/

**Comment by jcnorby** [comment]
I haven't seen any complaints about this and the upgrade could be inaccurate at any time so I'm closing this for now.
