### ISSUE TITLE
The branch which can be used?

### ISSUE THREAD

**Issue by crankler** [robomechanics/quad-sdk#283]
Hi, it's a great work from your team,  
but there have many branch and I wonder whicn I can use for the contact detection and proprioceptive terrain estimation as your paper said hare?
>Proprioception and Tail Control Enable Extreme Terrain Traversal by Quadruped Robots

**Comment by yanhaoy** [comment]
`add-tail-controller` contains most of the paper, but it's still a work in progress. There is a branch called `devel-terrain-estimation` that has basic terrain estimation stuff.

**Comment by yanhaoy** [comment]
Thank you for your attention. It is ongoing work and is not part of the release. But there is a branch called "devel-terrain-estimation" which has basic terrain estimation stuff.

**Comment by yanhaoy** [comment]
Thank you for your attention. It is ongoing work and is not part of the release. But there is a branch called `devel-terrain-estimation` which has basic terrain estimation stuff.

**Comment by crankler** [comment]
Yes, I will check `Quad Utils pkg` and  `devel-terrain-estimation` branch in these days, thank you for your reply here.
