### ISSUE TITLE
Global planner package not buiding

### ISSUE THREAD

**Issue by prakharg01** [robomechanics/quad-sdk#284]
Hello! This is great work for the legged robotics community. I was trying to build the packages and I'm not able to build this package due to some EIgen issues.:- global_body_planner

I have been using the master branch and not the devel branch as of now. The error is as follows:-
error: non-type template argument is not a constant expression
  Eigen::Matrix<double, 3, planner_config.num_collision_points>

However, I checked num_collision_points is defined as a static constant. Any help will be appreciated.

Thanks, 
Looking Forward

**Comment by ardalantj** [comment]
Hi ! Thank you for using quad-sdk. Please try using the main branch. Master branch has been deprecated. The main branch has passed our CI/CD pipeline so it should build fine.

**Comment by jcnorby** [comment]
Do let us know if switching branches fixes this issue - if you were already on main, a few questions:
- Did you run the setup.sh script as described in the installation instructions?
- What commands were you using (and in which directories) to build the SDK?

**Comment by prakharg01** [comment]
> Do let us know if switching branches fixes this issue - if you were already on main, a few questions that would help us pinpoint the issue:
> 
> * Did you run the setup.sh script as described in the installation instructions?
> * What commands were you using (and in which directories) to build the SDK?
> * What version of Eigen do you have on your machine (try `pkg-config --modversion eigen3`)?

Thanks

1) Yes I ran the setup.sh script.
2) I have followed these instructions:- https://github.com/robomechanics/quad-sdk/wiki/1.-Getting-Started-with-Quad-SDK#build
3) eigen3 -3.3.4

**Comment by jcnorby** [comment]
Hmm, that all seems to be in order. Could you provide a printout/screenshot of the full error? Also do the rest of the packages build as expected?

I suspect this is a versioning thing of some kind since as mentioned this code builds just fine from within our CI which starts from a clean environment. We have already been thinking of adding Docker support in the near future, which would resolve any versioning issues if that is indeed the cause.

**Comment by prakharg01** [comment]
> Thanks, but 2 packages are not building, ot

I have solved gazebo issues, now only the global body planner is having issues

**Comment by jcnorby** [comment]
Great! Out of curiosity, what was the solution for Gazebo?

I can poke around with the global_body_planner issue but I think the containerization is likely the best fix. You could try a temporary fix by hardcoding those particular consts, although if it is truly a versioning issue I suspect this will only cause a different error to pop up. Worth a shot though.

**Comment by jcnorby** [comment]
Two more followup questions:
- Do `sudo apt update` or `sudo apt upgrade` run into any issues? If your apt environment ran into issues something may not have installed or updated correctly while running `setup.sh`.
- What version of CMake do you have (`cmake --version`)?

**Comment by jcnorby** [comment]
Did one of these solve this issue?

**Comment by prakharg01** [comment]
No, it was something to do with my local gazebo settings. I had to update some of the packages.

Regarding the global body planner errors, I solved them by just hardcoding the values instead of using the static parameters. So this is a temp fix.
