### ISSUE TITLE
NMPC solving fail -12

### ISSUE THREAD

**Issue by gearguan** [robomechanics/quad-sdk#289]
Hi there, I can run
`roslaunch quad_utils quad_gazebo.launch`
and
`rostopic pub /robot_1/control/mode std_msgs/UInt8 "data: 1`
without problems, but when I run
`roslaunch quad_utils quad_plan.launch reference:=twist logging:=true`, I got **"NMPC solving fail -12"** :(

**Comment by jcnorby** [comment]
Hey there, glad you're trying things out! I think a few other folks are having a similar issue and some fixes have been suggested over on #288, so I'll direct the conversation there.
