### ISSUE TITLE
NMPC solving fail

### ISSUE THREAD

**Issue by xaioqi** [robomechanics/quad-sdk#302]
When I was running  robomechanics / quad-sdk, there were some problems I couldn't solve. I hope you can help me solve them. 1\roslaunch quad_utils quad_gazebo.launch
![image](https://user-images.githubusercontent.com/77819973/180368130-359f3102-2135-4e59-9ff6-6dd5b123f129.png)
![image](https://user-images.githubusercontent.com/77819973/180368175-07780829-354f-4446-8223-66a135e33d32.png)
2\
![image](https://user-images.githubusercontent.com/77819973/180368290-c45b0939-5761-4d5b-8af4-a0145b6db385.png)
![image](https://user-images.githubusercontent.com/77819973/180368309-09097d4e-7336-417a-89a5-068b815786bb.png)
3\
![image](https://user-images.githubusercontent.com/77819973/180368485-7f784053-242e-4ca3-86ae-a49ec458da7b.png)
![image](https://user-images.githubusercontent.com/77819973/180368507-8072ee76-d03a-4cf8-b5c8-8d4fba578e6b.png)
![image](https://user-images.githubusercontent.com/77819973/180368535-96d9362f-515e-4742-84e4-7f30fdc0d0d8.png)
running "roslaunch quad_ utils quad_ plan.launch reference:=gbpl logging:=true", the robot in rviz generates a planned path, but the robot will not act along the planned path. Terminate will generate a warning of "NMPC leaving fail" and continue to cycle
Thank you in advance

**Comment by jrenaf** [comment]
Hi, would you mind to check whether the solution to #288 is helpful or not.
