### ISSUE TITLE
CasADi's code-generation from matlab to C++

### ISSUE THREAD

**Issue by WDouven** [robomechanics/quad-sdk#312]
hello, I can achieve the CasADi's code-generation from matlab to C++, but how to ultilize the code generated in my project as a part of it ? Thanks in advance!

**Comment by jrenaf** [comment]
Hi, you can put Casadi generated files under [here](https://github.com/robomechanics/quad-sdk/tree/main/nmpc_controller/src/gen) and change what you want it to be loaded in `quad_nlp_utils.cpp` accordingly.

**Comment by WDouven** [comment]
thanks for your response, I will try it. Can it be realized that solve the NLP cost function without ipopt but with the generated code only?

**Comment by jrenaf** [comment]
You may take a reference at #304, but in general there are always a bunch of optimization solvers available to fit into our setup.

**Comment by WDouven** [comment]
Thanks, I will keep trying.
