### ISSUE TITLE
teleop_twist_keyboard package is missing

### ISSUE THREAD

**Issue by cmburgul** [robomechanics/quad-sdk#313]
Hello, 
    There is no teleop_twist_keyboard in quad-sdk/external. There is only teleop_twist_joy. What are the other ways to control the robot ?

**Comment by cmburgul** [comment]
I could not command by publishing on /cmd_vel

**Comment by jrenaf** [comment]
If you want to use keyboard to command the robot, just `apt-get install ros-melodic-teleop-twist-keyboard`

**Comment by cmburgul** [comment]
Thanks, that helps
