### ISSUE TITLE
Issues with replacing robot models

### ISSUE THREAD

**Issue by gearguan** [robomechanics/quad-sdk#317]
Hi there,
I created a new quadruped model with the same contents of the .yaml file in config as the spirit robot, no changes were made, and I did not modify any parameters in all controller.

When I run quad_plan.launch, the robot moves around and it shows that the nmpc solving failed.

Can this possibly be caused by what? Has anyone encountered a similar problem?
![test](https://user-images.githubusercontent.com/28438652/188088312-693a53ab-1cbe-43a2-89c5-0348edf27f9f.gif)

**Comment by AndrewZheng-1011** [comment]
Hey geargaun,
Not only do you have to change the robot model, but within the code itself you need to change the dynamics of the quadruped. A few of these would be in the: 
-  local planner
-  the matlab files in the nmpc script files to generate the dynamics of your robot
- Additionally enabling these options in the corresponding launch files
Issues #312 and issue #310 highlights some of the changes within the code that needs to be changed.

**Comment by gearguan** [comment]
@AndrewZheng-1011
Thank you very much, your suggestion is very helpful and the simulation works fine now. 👍
