### ISSUE TITLE
robot can not stand up in melodic_devel_ekf branch branch

### ISSUE THREAD

**Issue by aaLiujs** [robomechanics/quad-sdk#321]
Robot can not stand up in melodic_devel_ekf branch branch when I start up with "topics/state/estimate"

**Comment by ardalantj** [comment]
Hi @aaLiujs, currently the main branch is intended to be fully functional and tested for users. Other devel branches are experimental and may not necessarily be stable. Was there something in particular you were looking for in that branch?

**Comment by jcnorby** [comment]
Closing this branch due to lack of activity (also the main question was answered).

**Comment by aaLiujs** [comment]
邮件收到，O(∩_∩)O谢谢。
