### ISSUE TITLE
Transformation of /toe from /body frame

### ISSUE THREAD

**Issue by cmburgul** [robomechanics/quad-sdk#336]
Is there any way to get transformation of /toe from /body frame.

**Comment by jrenaf** [comment]
Hello @cmburgul, all the transformations we provide are given in quad_kd.cpp under quad_utils. We don't have /toe to /body transformation but you can write your own function in the format similar to other transformation functions provided there.

**Comment by cmburgul** [comment]
Thanks, that helps. 
I see the topic 'robot_1/state/grfs' gives foot position, from what frame ?

**Comment by jrenaf** [comment]
That's in the global frame.

**Comment by jcnorby** [comment]
Seems this is resolved so closing for now. Also note that many transforms are available through tf, and quad_kd.cpp can be expanded for other transforms pretty easily since most of the leg FK/IK is already implemented.
