### ISSUE TITLE
Slow the stand up

### ISSUE THREAD

**Issue by elpimous** [robomechanics/quad-sdk#339]
Hi the team.
Is it possible to show down the stand up process?
Thanks the team.

**Comment by jcnorby** [comment]
Yep, that parameter is a member of the RobotDriver class (declared [here](https://github.com/robomechanics/quad-sdk/blob/b04d4f7658215da018b4843c98f49e50b1b339c6/robot_driver/include/robot_driver/robot_driver.h#L270)) and can be overriden however you prefer. We should probably make it a ROS parameter at some point...

**Comment by elpimous** [comment]
👌
