### ISSUE TITLE
Error in legs/joints order?! 

### ISSUE THREAD

**Issue by elpimous** [robomechanics/quad-sdk#342]
Hello
Is there an error in Readme, regarding to legs joints order?
The joint arrays in spirit_msgs::RobotState are defined such that indices 0 = abad0, 1 = hip0, 2 = knee1, 3 = abad1, 4 = hip1, 5 = knee12, 6 = abad2, 7 = hip2, 8 = knee2, 9 = abad3, 10 = hip3... 

Abad0, hip0, knee0.. Same index for the chain, no?

**Comment by jcnorby** [comment]
Good catch, updated (to clarify for others this was in the FAQ section of the Wiki, not any particular readme file).

**Comment by elpimous** [comment]
👍
