### ISSUE TITLE
Bad standup on hardware robot (not spirit, go or A1!) 

### ISSUE THREAD

**Issue by elpimous** [robomechanics/quad-sdk#353]
Hello the team.
Thanks for help.
Now, i can make my ylo2 robot move for a standup.
URDF and SDF ok, inertias and gravity ok.

When running robot_hardware.launch, the robot automatically standup (after a homemade zero calibration = ok)
During standup, all joints have correct direction, imu seems ok,

But robot is pushed backward : it stands up, with anything like 45° up-rear.
Any idea ?

Perhaps should I modify standup pose (joints).
If yes, where?

**Comment by elpimous** [comment]
https://youtu.be/LNuAhMMIKZ0

**Comment by elpimous** [comment]
hello, well even with correct servos direction and correct sit down and standup params : 
```
ylo2@ylo2-UP-WHL01:~$ rosparam get /robot_driver/sit_joint_angles

- 0.165
- 0.59
- 1.36

ylo2@ylo2-UP-WHL01:~$ rosparam get /robot_driver/stand_joint_angles
- 0.0
- 0.5213467868148791
- 1.09094730619712
```
The robot put it legs right, and perpendicular to body (my real rezero joints)

I don't anderstand what happens..  Any small idea to share to help me progress ?!

**Comment by elpimous** [comment]
Here is my steps : 
Ylo2 robot is permanent zeroed with legs parallel, right, and perpendicular to body
![Ylo-2_urdf](https://user-images.githubusercontent.com/8529940/224494720-230a75ba-6ea1-4d54-af9a-1fc8e11e8ccb.png)

Before running code, robot is in a sit position : 
![Screenshot_20230311_170405_com google android apps photos](https://user-images.githubusercontent.com/8529940/224494813-a94e0de2-dd0a-49fa-a0f7-a00696ab56e4.jpg)

**Comment by elpimous** [comment]
Or perhaps in hardware mode, initial pose and stand are set in other place?  If yes, didn't find...

**Comment by jrenaf** [comment]
Hello @elpimous, it's great to see you are trying quad-sdk on new quadruped platform! The stand-up motion is hardcoded in robot_driver and it might be impacted by different initialization configuration. You might directly change that part [here](https://github.com/robomechanics/quad-sdk/blob/main/robot_driver/src/robot_driver.cpp#L418) .

**Comment by elpimous** [comment]
Hi @jrenaf
Yes I saw that.
My question is : does the hardware use sit and params, from quad_util/config/ylo2_ config.yaml

And how is calibrate spirit?

**Comment by elpimous** [comment]
Hey, i can confirm the following things : 
- any changes on **sit_joint_angles** param, in a1.yaml ( https://github.com/robomechanics/quad-sdk/blob/b04d4f7658215da018b4843c98f49e50b1b339c6/quad_utils/config/a1.yaml#LL76C2-L76C36 )
are without effect on hardware.

(changes are ok on a1 simulation )

My urdf is a1, and i call robot_type = a1.

**Comment by elpimous** [comment]
Hello the team.
Found an error in my joints order...
Working now on joint direction, and initial pose.. Next soon.

**Comment by hassan-mehmood1** [comment]
Hi @elpimous ,
Can you tell us which branch you are using ?
