### ISSUE TITLE
Questions about tuning "my_robot".yaml file, for real working robot

### ISSUE THREAD

**Issue by elpimous** [robomechanics/quad-sdk#354]
Hi all.

### QUESTIONS ABOUT KP : KD

1/ When launching `robot_driver.launch` , legs move to their initial pose, thanks to param : `sit_joint_angles`
During this process, the variable **control_mode_** takes the value 0: **SIT**

2/ I send the standup command : `rostopic pub -1 /control/mode std_msgs/UInt8 "data: 1"`
it changes **control_mode_** value to 1: **READY**  then 2: **SIT_TO_READY**
The robot tries to standup, thanks to param : `stand_joint_angles`

But lot of tremblings under motors.
### Do you have tips to start from secure params, and improve slowly ?!

stand_kp: [5, 5, 5]
stand_kd: [0.05, 0.05, 0.05]

Anything like this, for a standup moves ?

**Comment by jrenaf** [comment]
Hello @elpimous, you can tune the PD through visualization of motor position by letting live_plot to be true, which will open PlotJuggler that can show the instantenous position tracking by each motor.

**Comment by elpimous** [comment]
@jrenaf  "Do you have any idea how you want to do estimation on your robot in the future?"
Sorry, don't anderstand your question . Would you mind explain me ?

Thanks for tips !

### Here was my PID steps : 
1 - put **kd** to 0
2 - find best **kp** value : highter is better, until i see motors trembling, then I lower a bit to erase any tremblings.
3 - let **kp** at it best, and do same with **kd**, until i see best response, and no tremblings.
actually, for now, I'm at this point : 

```
sit_kp: [1, 1, 1]
sit_kd: [0.1, 0.1, 0.1]
stand_kp: [3.5, 3.5, 3.5]
stand_kd: [1.3, 1.3, 1.3]
```
