### ISSUE TITLE
how to estimate robot body pose, without camera(s) Help !

### ISSUE THREAD

**Issue by elpimous** [robomechanics/quad-sdk#356]
Hi friends.
quad-sdk estimates body pose with help of cameras..

### Can't it be made only with IMU return ?

Did anyone here did it without camera ?
Could I ask any help, from a "newbie", to help my robot walk ?
Thanks all.
Vincent

**Comment by ologandavid** [comment]
Do you mean just using the simulation ground truth for your body pose?

**Comment by elpimous** [comment]
hi big thanks for help.
Well, don't know ! 
Using code on my real robot.
It stand up correctly, but i'd like to make it walk only with the robot itself, without aly mocap or cameras.
All ideas would help me a lot

**Comment by ologandavid** [comment]
@elpimous Does your robot currently have an IMU? Assuming the robot doesnt slip, you could integrate the IMU to get a position and velocity estimate. This might drift, but if you're impatient, this might be your best bet.

**Comment by elpimous** [comment]
PS I have a t265, place on robot bottom (d435 front) 
I don't see in code how to use t265 ?!!

**Comment by ologandavid** [comment]
That sounds right, feeding in your IMU information into last_robot_state_msg should work. I'll keep you updated on the progress of EKF estimation!

**Comment by elpimous** [comment]
Didn't find it.
Discussion section, check
