### ISSUE TITLE
[mesh_to_grid_map_node]  died. mesh_to_grid 

### ISSUE THREAD

**Issue by aCodeDog** [robomechanics/quad-sdk#361]
When I launch quad_gazebo.launch file,it occurs：
`double free or corruption (out)`

`[ INFO] [1681922778.146408235]: Loading sim robot driver`
`[INFO] [1681922778.183861, 0.000000]: Loading model XML from ros parameter robot_description_sdf`
`[INFO] [1681922778.192351, 0.000000]: Waiting for service /gazebo/spawn_sdf_model`
`[mesh_to_grid_map_node-3] process has died [pid 40533, exit code -6, cmd /home/wang/Quad-sdk/devel/lib/quad_utils/mesh_to_grid_map_node __name:=mesh_to_grid_map_node 
__log:=/home/wang/.ros/log/b4200fcc-ded1-11ed-b5fa-8d045a63f47b/mesh_to_grid_map_node-3.log].
log file: /home/wang/.ros/log/b4200fcc-ded1-11ed-b5fa-8d045a63f47b/mesh_to_grid_map_node-3*.log 
`

And I found here in `line 201: mesh_to_grid_map_converter.cpp` has something wrong:
`pcl::PolygonMesh mesh_from_file;` 
 ` pcl::io::loadPolygonFilePLY(path_to_mesh_to_load, mesh_from_file); ` 

But I don't know why this function causes this node died.

**Comment by jcnorby** [comment]
Sounds like something in your install didn't go quite right. That class prints the path to the world file it expects in the constructor (line 31) - can you verify that this path does actually point to a real .ply file? We may be missing an existence check which could cause an error like this.

**Comment by selvingarciag96** [comment]
@aCodeDog Any updates on this?

**Comment by aCodeDog** [comment]
> Sounds like something in your install didn't go quite right. That class prints the path to the world file it expects in the constructor (line 31) - can you verify that this path does actually point to a real .ply file? We may be missing an existence check which could cause an error like this.

I have verified that this path does actually point to a real .ply file. I create a new cpp file to read it, and it works well.
Maybe my Pcl lib has some problem. Finally, I re-install PCL, and everythins is ok.

**Comment by CangMingRui** [comment]
May I ask which version of PCL you are using? I tried reinstalling PCL, but this issue still exists
