### ISSUE TITLE
terminate called after throwing an instance of 'std::out_of_range'   what():  GridMap::atPosition(...) : Position is out of range.

### ISSUE THREAD

**Issue by dbdxnuliba** [robomechanics/quad-sdk#373]
![image](https://github.com/robomechanics/quad-sdk/assets/13350158/23d5bec6-3596-4e61-aba9-75dce77227b8)

**Comment by ologandavid** [comment]
Hi @dbdxnuliba,
The robot's position is outside the allowable map, hence the error. Recentering the robot should help. 

Best, 
David Ologan

**Comment by dbdxnuliba** [comment]
thanks
