### ISSUE TITLE
An error occurred during the initial compilation process

### ISSUE THREAD

**Issue by nanbwrn** [robomechanics/quad-sdk#377]
I encountered an undefined reference error during compilation. The specific content is as follows: Thank you for your reply:
![e9c36df9d5ea7cb312050e9d9cc0929](https://github.com/robomechanics/quad-sdk/assets/132453617/8c7dff97-8ece-40c9-9d3f-ba046dd6b609)

**Comment by nanbwrn** [comment]
Hi @ologandavid ，
thank you for your reply. I am using Ipopt-3.12.7,and HSL for IPOPT as shown in the following figure,
![HSl](https://github.com/robomechanics/quad-sdk/assets/132453617/d6664a99-1919-4de3-aef2-ac8ea1e6ca08)

**Comment by ologandavid** [comment]
Hi @nanbwrn,
The Ipopt version that you should be using is 3.13. That's probably contributing to the fact that the initial compliation is failing. Try requesting ma27 or ma57 solver from coinhsl. Let me know if that resolves your issue.

Best, 
David

**Comment by nanbwrn** [comment]
Thank you for your enthusiastic response. I have solved this problem and used a new coinhsl that includes ma57 to overwrite the original coinhsl.And it has been compiled successfully
