### ISSUE TITLE
Error reporting when I run roslaunch quad_utils quad_gazebo.launch 

### ISSUE THREAD

**Issue by nanbwrn** [robomechanics/quad-sdk#378]
The following error occurred in the terminal when I run roslaunch quad_ utils quad_gazebo. launch.May I ask if anyone has encountered it before? Thank you for your reply
![roslaunch报错](https://github.com/robomechanics/quad-sdk/assets/132453617/10e96986-b054-478f-84c8-60e8e68e7e85)
![rviz图像](https://github.com/robomechanics/quad-sdk/assets/132453617/8927c47b-d7da-4451-a759-133b0e18ce62)

**Comment by ologandavid** [comment]
Hi @nanbwrn,
Sorry for the late reponse, this looks similar to a problem I resolved in the past. Do you still need help with this, and if so, could I see your rviz settings (display tab), and if possible general information about your system (what branch are you currently using etc.) Checking the gazebo model path in your bash file could also help.

Best, 
David Ologan

**Comment by pranavgo** [comment]
@nanbwrn I am facing the same issue. Can you please tell me how you fixed it? Thanks.

**Comment by nanbwrn** [comment]
1.I updated Gazebo at that time:
sudo apt upgrade libignition-math2
2.Then, I updated this .sh file, opened the terminal at the quad_simulator directory, and entered: ./setup_deps.sh
