### ISSUE TITLE
Help about noetic devel ekf branch

### ISSUE THREAD

**Issue by elpimous** [robomechanics/quad-sdk#380]
@ologandavid,

1 does your actual code work on a real robot?
(ready to test on mine)

2 this ekf version removes the need of mocap or t265, correct?

3 do i need foot sensors, here? (dont have)
Thanks friend.
Vincent.

**Comment by elpimous** [comment]
compilation ok, but errors when tests : 

```
roslaunch quad_utils load_global_params.launch load_robot_params:=true
cd ~/catkin_ws
catkin run_tests
```

![Capture d’écran de 2023-06-16 22-53-36](https://github.com/robomechanics/quad-sdk/assets/8529940/eb01179b-8afe-4efb-a52f-775ddae9a7f4)

**Comment by elpimous** [comment]
small up guys ?

**Comment by ologandavid** [comment]
Hi @elpimous,
Please hold off for now on testing that branch on your robot. It hasn't been hardware tested and there are still a few bugs I'm currently working through. (1) Yes it should remove the need for mocap or the tracking camera. (2) and no you should't (3).

Best, 
David Ologan

**Comment by elpimous** [comment]
Thanks friend...
I'll  wait.

**Comment by elpimous** [comment]
@ologandavid ,
Hi friend,
What could be the best branch to rest your controller on my real robot ?
My hardware_interface is ready.
I encounter some errors with melodic_devel_go_outdoors branch (on my noetic system)

**Comment by elpimous** [comment]
@ologandavid  please up.

**Comment by ardalantj** [comment]
I will close this issue since state estimation this will be part of an upcoming release.

**Comment by dhajnes** [comment]
Hi @ologandavid, it has been a few weeks since you mentioned the bugs and @ardalantj mentioned that state estimation will be part of an upcoming release. Do you have any release time estimates? In a week? Month? 4 months? I was looking for some roadmap and didn't find any.

**Comment by ologandavid** [comment]
[See](https://github.com/robomechanics/quad-sdk/pull/338#issuecomment-1652470683) . Currently testing our implementation on hardware, once its tested, everything should be good to go.

**Comment by elpimous** [comment]
Exciting!!!!
Please share sole hardware videos, 😍😍
