### ISSUE TITLE
May I ask how the torque applied about the pitch axis in the paper is calculated（𝜏_𝑝）？

### ISSUE THREAD

**Issue by nanbwrn** [robomechanics/quad-sdk#381]
I have been studying a paper written by your team recently and have benefited greatly. （Fast Global Motion Planning for Dynamic Legged Robots）, I have the following questions. Can you help me answer them?
a) There is a formula in the paper that calculates acceleration, do I understand it correctly
![ad7e068e0b1814f6af94026121efb75](https://github.com/robomechanics/quad-sdk/assets/132453617/a39291de-0b10-4486-9945-41c135c42949)

b) and there is a torque applied about the pitch axis.  I am not quite sure about this. May I ask how this is calculate.

**Comment by ardalantj** [comment]
@jcnorby Any thoughts on this?

**Comment by jcnorby** [comment]
This term was essentially bounding the net angular acceleration about the pitch axis of the robot - it isn't tied to any particular actuator but generally ensures that pitch accelerations aren't excessive.

That said, this term is no longer present in the QuadSDK implementation, as pitch is computed to align with a filtered terrain normal to ensure that the likelihood all feet can reach the ground is maximized. In practice this yields better solutions than adding this term to the random sampler, and is sufficiently accurate for a global planner (local planners can refine this as needed). Hope that helps!
