### ISSUE TITLE
Problems of a local planner on a real robot Unitree Go1

### ISSUE THREAD

**Issue by mfclabber** [robomechanics/quad-sdk#383]
Hello. I had a problem with the local planner on a real robot .. . When I run my
"remote_driver.launch" and "roslaunch quad_utils quad_plan.launch reference:=twist logging:=true" 
I get this situation. The robot is standing still, but its trajectory is moving up. 
@jcnorby , How can I fix this?
![Screenshot from 2023-06-23 18-09-38](https://github.com/robomechanics/quad-sdk/assets/118126641/c97ab112-22e2-463b-9302-5f705992cb50)
![Screenshot from 2023-06-23 18-53-03](https://github.com/robomechanics/quad-sdk/assets/118126641/8bdc17ce-5ab9-4fd9-910c-34f60e9cbb9c)
![Screenshot from 2023-06-23 18-53-04](https://github.com/robomechanics/quad-sdk/assets/118126641/f427b705-dbcd-4354-8483-6172625a3054)

**Comment by elpimous** [comment]
@mfclabber how did you solve your problem?

**Comment by mfclabber** [comment]
@elpimous The problem was in the robot's IMU, namely in the wrong coordinates relative to the robot. It was also necessary to adapt NMPC for Unitree Go1. These changes can be seen in my[ repository](https://github.com/mfclabber/quad-sdk_go1))

**Comment by elpimous** [comment]
Thanks for answer.
