### ISSUE TITLE
How to run  matlab scripts correctly in the quad_logger

### ISSUE THREAD

**Issue by nanbwrn** [robomechanics/quad-sdk#385]
What steps are required to run scripts in quad logs in Matlab?
 I added these two variables according to the steps in the Wiki.
 I added 
trialName='quad_log ';%(The file name of the bag)
namespace='robot_ 1 '; 
The values of these two variables encountered an error while running proscessLog. m
![71e32f58d926309083e9bc8bfb9be5c](https://github.com/robomechanics/quad-sdk/assets/132453617/c1b91dfe-5797-4bb5-9e6c-d01a606ff3e9)
![abce35fbc56b63756ea24cd5ddafc45](https://github.com/robomechanics/quad-sdk/assets/132453617/f4115667-afab-4f80-9255-629b2af1a70c)
What are the detailed steps for running MATLAB scripts? Thank you

**Comment by nanbwrn** [comment]
Hi @ologandavid ,

Thank you for your prompt response.
I followed the steps you mentioned and did it again.
The general steps I ran are as follows:
I ran it in MATLAB on a Windows system. I copied the "quad_logger/scripts" folder from the "quad_sdk" to MATLAB in my Windows system, 
and I also copied the "robot_1_quad_log_.bag" file(decompressed file) into it .

After running the program, I encountered the following error:
How can this be resolved?

![431ae61195d94f5d06182c032dd56ef](https://github.com/robomechanics/quad-sdk/assets/132453617/dcf9a56c-a730-4a52-b04e-e9cd7648f08d)

**Comment by ologandavid** [comment]
Hi @nanbwrn,
If you're looking at a bag file you recorded in sim feel free to comment those lines out given that your state estimate topic  should be empty. In simulation, your state comes directly from gazebo. 

To debug, I would first check to make sure that stateGroundTruth is populated, (comment everything else out) just to make sure matlab is recognizing your desired bag. Did the UI work for you when selecting a bag?

Best,
David

**Comment by nanbwrn** [comment]
thank you for you response.
 I'll continue to give it a try.
