### ISSUE TITLE
run roslaunch quad_utils quad_visualization.lauch , appears blank

### ISSUE THREAD

**Issue by nanbwrn** [robomechanics/quad-sdk#386]
When I run roslaunch quad_utils quad_visualization.launch, the RViz interface is blank. 
However, when I run gazebo.launch, the robot model is displayed correctly, and other programs also work fine.
Below is a video of this operation

https://github.com/robomechanics/quad-sdk/assets/132453617/04643cc3-28d5-4e3e-881b-7a585bb6001f

**Comment by ologandavid** [comment]
Hi @nanbwrn,
Thats to be expected. The launch file quad_gazebo.launch runs the entire stack (except for planning), so it launches the rviz interface, loads in the robot and launches robot driver etc. 

Quad_visualization.launch only runs the rviz visualization plugins for the robot, so it doesn't run the rest of the stack. Typically, quad_visualization is used if you want to run visualize a recorded bag file. 

See an example here: https://github.com/robomechanics/quad-sdk/wiki/3.-Processing-Data-Logs

Best, 
David
