### ISSUE TITLE
Loading Custom Terrain Map

### ISSUE THREAD

**Issue by nanbwrn** [robomechanics/quad-sdk#391]
When I followed the steps in this wiki to create my own map model, an odd situation occurred.
I encountered this situation before adjusting the coordinate system. 
![custom Terrain map_go1](https://github.com/robomechanics/quad-sdk/assets/132453617/a3b4194e-9204-4e1a-bb4f-070e47425b9f)

After adjusting the coordinate system, the robot falls down right after opening the simulation.

https://github.com/robomechanics/quad-sdk/assets/132453617/81df0237-f24e-470a-acdb-cf5cab307db6

https://github.com/robomechanics/quad-sdk/assets/132453617/71f407f2-d2bc-4742-92e3-5d8a07f505b6

**Comment by nanbwrn** [comment]
I solved this problem by adjusting the origin of the  terrain map.

**Comment by ruihuang1124** [comment]
> I solved this problem by adjusting the origin of the terrain map.

Hi friend, @nanbwrn , I encounter a similar problem, can you briefly describe how you adjust the origin of the terrain map and finally solve this problem?
