### ISSUE TITLE
Proprioceptive State Estimator Inclusion

### ISSUE THREAD

**Issue by varunagrawal** [robomechanics/quad-sdk#399]
Thank you for this great work!

I was wondering if there is interest in a proprioceptive state estimator being included. I built one for the Anymal C and Unitree A1 quadrupeds [paper](https://arxiv.org/abs/2209.05644) so I should be able to add it here as well if it's something that would be useful.

**Comment by ologandavid** [comment]
Feel free to make a pull request if you have it working within the framework!
