### ISSUE TITLE
local planned can not build successfully,see pics below:

### ISSUE THREAD

**Issue by Crazywjw** [robomechanics/quad-sdk#409]
/usr/bin/ld: warning: libcoinhsl.so.0, needed by /usr/local/lib/libipopt.so.1, not found (try using -rpath or -rpath-link)
![image](https://github.com/robomechanics/quad-sdk/assets/50315623/644c246a-518a-4fa5-b867-c010f1fa9c8e)
![image](https://github.com/robomechanics/quad-sdk/assets/50315623/718a6619-a929-4eca-b3e7-9e0bcfdbc50a)

**Comment by ologandavid** [comment]
Hi @Crazywjw, 
This could be a combination of issues, I think the first would be to make sure you requested the right version of the solver, I'm using ma27, so I can confirm that that version works. Next, take a look at these commits from this pending [pull request](https://github.com/robomechanics/quad-sdk/pull/408/commits/15af19a209332b4be6ce72b1cba458220fc21e7e). Try updating these lines in the code, and then rerunning the setup.sh script. and then retrying the build. If the issue persists, please follow up here. 

Best, 
David

**Comment by ologandavid** [comment]
Hi, I'm following up on this issue, otherwise I'll mark it as closed. 

Best, 
David Ologan
