### ISSUE TITLE
Show estimated terrain

### ISSUE THREAD

**Issue by DonovanZhu** [robomechanics/quad-sdk#413]
Hi:

I notice an excellent project **Proprioception and Tail Control Enable Extreme Terrain Traversal by Quadruped Robots** based on quad-sdk. In this project the estimated terrain is shown like the following photo:
![image](https://github.com/robomechanics/quad-sdk/assets/49983377/e339837a-6d51-4369-ac8c-93fc8bcfe4dc)

Unfortunately, I can't find the open source code for that project. Is this terrain estimation method included in this SDK? Or does it have an API to display real-time estimated terrain?

Thanks!

**Comment by ologandavid** [comment]
Hi, @DonovanZhu, 
The code for this project should be in branch add-tail-controller-latest within Quad-SDK. For more specific questions, I would recommend you reach out directly to @yanhaoy, who authored the paper and can probably provide more insight. 

Best, 
David Ologan

**Comment by DonovanZhu** [comment]
> Hi, @DonovanZhu, The code for this project should be in branch add-tail-controller-latest within Quad-SDK. For more specific questions, I would recommend you reach out directly to @yanhaoy, who authored the paper and can probably provide more insight.
> 
> Best, David Ologan

Thank you so much for your reply @ologandavid! It helps a lot.
