### ISSUE TITLE
with ROS2？

### ISSUE THREAD

**Issue by yccckid** [robomechanics/quad-sdk#421]
this work can be perfomed by ROS2?

**Comment by ologandavid** [comment]
Hi @yccckid, 
Currently, the code base only supports ROS1. However, the lab is planning on converting the code base to ROS2 over the summer, so look forward to those additions!

Best, 
David Ologan

**Comment by zhxiaoyu218** [comment]
Hi, David,
we'd like to work on ROS2 for GO2, as their sdk naturely support dds. Would mind if we build on top of this repo.

**Comment by ologandavid** [comment]
Hi @zhxiaoyu218, 
That sounds great! As a lab, we'd like to encourage others to build on the repo to suit their own purposes. If you're using this work in an academic context, please cite the following [publications.](https://github.com/robomechanics/quad-sdk?tab=readme-ov-file#publications)

Additionally, if you get a working implementation in ROS2 feel free to make a pull request and I can formally add it to the repo. I've started updating the repo to ROS2 as well, but if you would like to give it a shot before I get to it feel free. 

If you would like, we could schedule a call and we can talk through the process and work together on this. 

All the best, 
David Ologan

**Comment by zhxiaoyu218** [comment]
> Hi @zhxiaoyu218, That sounds great! As a lab, we'd like to encourage others to build on the repo to suit their own purposes. If you're using this work in an academic context, please cite the following [publications.](https://github.com/robomechanics/quad-sdk?tab=readme-ov-file#publications)
> 
> Additionally, if you get a working implementation in ROS2 feel free to make a pull request and I can formally add it to the repo. I've started updating the repo to ROS2 as well, but if you would like to give it a shot before I get to it feel free.
> 
> If you would like, we could schedule a call and we can talk through the process and work together on this.
> 
> All the best, David Ologan

  sounds great! I am so glad to work together on this. I have emailed your personal email.
