### ISSUE TITLE
The map loaded in the simulation has been simplified

### ISSUE THREAD

**Issue by nanbwrn** [robomechanics/quad-sdk#422]
hi,everyone

I created a map in SolidWorks that includes rebar, but when I start the simulation and load the map into rviz, the rebar (which has a 
diameter of 10mm) doesn't show up. It seems like the map might have been simplified. Has anyone else encountered this issue? What parameters do I need to adjust to make the rebar visible?

thank you very much.

![7be01a34e8d80c4eb17eeb2be58a231](https://github.com/robomechanics/quad-sdk/assets/132453617/69ca9344-4470-43ef-97d5-23a9256d95b1)

![71b3b5813f90e2b06f25340f58597c4](https://github.com/robomechanics/quad-sdk/assets/132453617/d737971a-73d3-4d09-a9ec-ab43cee71730)

**Comment by nanbwrn** [comment]
ok

**Comment by nanbwrn** [comment]
ok,I'm also a newcomer to this field, so let's learn from each other.

**Comment by ologandavid** [comment]
Hi @nanbwrn @ruihuang1124,
When you launch visualization, i.e quad_gazebo.launch try adding the flag gui:=true. The rebar you've added might spawn into gazebo, and not rviz, since rviz is used primarily for visualization instead of an actual representation of the environment. 

Best, 
David Ologan

**Comment by ologandavid** [comment]
Updates on this before I go ahead and close it as completed?

**Comment by nanbwrn** [comment]
I apologize for the late response; I've been held up with some matters recently.
