### ISSUE TITLE
ID node couldn't find the correct ref state

### ISSUE THREAD

**Issue by elpimous** [robomechanics/quad-sdk#424]
![Capture d’écran de 2024-05-12 22-54-27](https://github.com/robomechanics/quad-sdk/assets/8529940/59c3038c-045b-4ebc-855d-b2394d96c68c)

Edit: Solved. bad robot dimensions

**Comment by elpimous** [comment]
commands : 

roslaunch quad_utils robot_driver.launch mocap:=false estimator:=ekf_filter namespace:=robot_1 robot_type:=ylo2

roslaunch quad_utils remote_driver.launch mocap:=false robot_type:=ylo2

roslaunch quad_utils quad_plan.launch reference:=twist logging:=false

**Comment by ryanz2023** [comment]
how do you solve that?
