### ISSUE TITLE
NMPC solving fail

### ISSUE THREAD

**Issue by RoCos206** [robomechanics/quad-sdk#428]
I solved loading the robot and standing it up, but when I try to run twist, the nmpc solving fail problem occurs.

[ WARN] [1722911802.924340090, 12.319000000]: NMPC solving fail

**Comment by ologandavid** [comment]
Hi @RoCos206, 
Can you provide a little more information on exactly what you're doing? What commands are you running, the branch name, solver version you're using etc. 

Best, 
David Ologan

**Comment by RoCos206** [comment]
I'm using noetic devel, and while loading the robot I get nmpc soiving fail when I use command roslaunchquad_utilsquad_plan.launch reference:=twistlogging:=true. How can I check the solver version?

**Comment by RoCos206** [comment]
Solved! It was a hsl problem

**Comment by ologandavid** [comment]
Happy to hear it!
